version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"

  build:
    commands:
      - echo "Build phase"
      - ls -R   # DEBUG (VERY IMPORTANT)

artifacts:
  files:
    - '**/*'
  discard-paths: no
